import Provider from "@/graphql/Provider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import ProviderAuth from "@/components/ProviderAuth";
import NavBarNavigation from "@/components/NavBarNavigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<ProviderAuth>
					<NavBarNavigation />
					<Provider>
						<div className='md:container md:mx-auto'>{children}</div>
					</Provider>
				</ProviderAuth>
				<Toaster />
			</body>
		</html>
	);
}
